services:
  iris:
    build: .
    ports:
      - 52773
      - 1972
    working_dir: /home/irisowner/typeorm-iris
    user: "51773"
    command:
      - --after
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
    volumes:
      - ./:/home/irisowner/typeorm-iris
      - /home/irisowner/typeorm-iris/node_modules
      - /home/irisowner/typeorm-iris/build
