name: Tests
on:
  push:
    branches:
      - master
jobs:
  iris:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 22
          - 24
        image:
          - latest-em
          - latest-preview
    services:
      iris:
        image: containers.intersystems.com/intersystems/iris-community:${{ matrix.image }}
        ports:
          - 1972:1972
        options: >-
          --name iris
          --health-cmd "/usr/irissys/dev/Cloud/ICM/waitReady.sh -m 1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: docker exec iris iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - run: npm ci
      - run: npm run build
      - run: npm run test
